NextVerse COMPANY INFORMATION
COMPANY_EMAIL = NextVerse.101@gmail.com
COMPANY_PASSWORD: Iamamember
GITHUB_PASSWORD: 1amamember$$$%%%###
GITHUB_USERNAME : NEXTVERSE101
ELASTICE_EMAIL_ACCOUNT: Google Account For NextVerse
ELASTICE_EMAIL_ACCOUNT_FOR_TWO_FACTOR_AUTHENTICATION=NextVerse.101@gmail.com
ELASTICE_EMAIL_ACCOUNT_BACKUP_CODE: 198183 #Note To Be Used Only Once
ELASTICE_EMAIL_USERNAME = NextVerse.101@gmail.com #For The Email API
ELASTICE_EMAIL_PASSWORD = 8EC364D7489D8B7C593E46AD7FF88EFDDEE3 #For The Email API